use crate::pokemon::ID;

const fn id(num: u16) -> ID {
    ID::new(num).unwrap()
}

pub const STAT_HP: u8 = 1;
pub const STAT_ATTACK: u8 = 2;
pub const STAT_DEFENSE: u8 = 3;
pub const STAT_SPECIAL_ATTACK: u8 = 4;
pub const STAT_SPECIAL_DEFENSE: u8 = 5;
pub const STAT_SPEED: u8 = 6;

// remove at some point
macro_rules! ids {
    ($($name: ident $value: literal)+) => {
        $(pub const $name: ID = id($value);)+
    };
}

ids!(
    POKEMON_PIKACHU     25
    POKEMON_MAROWAK     105
    POKEMON_DITTO       132
    POKEMON_SHEDINJA    292
    POKEMON_CLAMPERL    366
);

// #[repr(u16)]
// #[derive(Clone, Copy, Debug, PartialEq)]
// pub enum Move {
//     Pound = 1,
//     KarateChop,
//     DoubleSlap,
//     CometPunch,
//     MegaPunch,
//     PayDay,
//     FirePunch,
//     IcePunch,
//     ThunderPunch,
//     Scratch,
//     ViceGrip,
//     Guillotine,
//     RazorWind,
//     SwordsDance,
//     Cut,
//     Gust,
//     WingAttack,
//     Whirlwind,
//     Fly,
//     Bind,
//     Slam,
//     VineWhip,
//     Stomp,
//     DoubleKick,
//     MegaKick,
//     JumpKick,
//     RollingKick,
//     SandAttack,
//     Headbutt,
//     HornAttack,
//     FuryAttack,
//     HornDrill,
//     Tackle,
//     BodySlam,
//     Wrap,
//     TakeDown,
//     Thrash,
//     DoubleEdge,
//     TailWhip,
//     PoisonSting,
//     Twineedle,
//     PinMissile,
//     Leer,
//     Bite,
//     Growl,
//     Roar,
//     Sing,
//     Supersonic,
//     SonicBoom,
//     Disable,
//     Acid,
//     Ember,
//     Flamethrower,
//     Mist,
//     WaterGun,
//     HydroPump,
//     Surf,
//     IceBeam,
//     Blizzard,
//     Psybeam,
//     BubbleBeam,
//     AuroraBeam,
//     HyperBeam,
//     Peck,
//     DrillPeck,
//     Submission,
//     LowKick,
//     Counter,
//     SeismicToss,
//     Strength,
//     Absorb,
//     MegaDrain,
//     LeechSeed,
//     Growth,
//     RazorLeaf,
//     SolarBeam,
//     PoisonPowder,
//     StunSpore,
//     SleepPowder,
//     PetalDance,
//     StringShot,
//     DragonRage,
//     FireSpin,
//     ThunderShock,
//     Thunderbolt,
//     ThunderWave,
//     Thunder,
//     RockThrow,
//     Earthquake,
//     Fissure,
//     Dig,
//     Toxic,
//     Confusion,
//     Psychic,
//     Hypnosis,
//     Meditate,
//     Agility,
//     QuickAttack,
//     Rage,
//     Teleport,
//     NightShade,
//     Mimic,
//     Screech,
//     DoubleTeam,
//     Recover,
//     Harden,
//     Minimize,
//     Smokescreen,
//     ConfuseRay,
//     Withdraw,
//     DefenseCurl,
//     Barrier,
//     LightScreen,
//     Haze,
//     Reflect,
//     FocusEnergy,
//     Bide,
//     Metronome,
//     MirrorMove,
//     SelfDestruct,
//     EggBomb,
//     Lick,
//     Smog,
//     Sludge,
//     BoneClub,
//     FireBlast,
//     Waterfall,
//     Clamp,
//     Swift,
//     SkullBash,
//     SpikeCannon,
//     Constrict,
//     Amnesia,
//     Kinesis,
//     SoftBoiled,
//     HighJumpKick,
//     Glare,
//     DreamEater,
//     PoisonGas,
//     Barrage,
//     LeechLife,
//     LovelyKiss,
//     SkyAttack,
//     Transform,
//     Bubble,
//     DizzyPunch,
//     Spore,
//     Flash,
//     Psywave,
//     Splash,
//     AcidArmor,
//     Crabhammer,
//     Explosion,
//     FurySwipes,
//     Bonemerang,
//     Rest,
//     RockSlide,
//     HyperFang,
//     Sharpen,
//     Conversion,
//     TriAttack,
//     SuperFang,
//     Slash,
//     Substitute,
//     Struggle,
//     Sketch,
//     TripleKick,
//     Thief,
//     SpiderWeb,
//     MindReader,
//     Nightmare,
//     FlameWheel,
//     Snore,
//     Curse,
//     Flail,
//     Conversion2,
//     Aeroblast,
//     CottonSpore,
//     Reversal,
//     Spite,
//     PowderSnow,
//     Protect,
//     MachPunch,
//     ScaryFace,
//     FeintAttack,
//     SweetKiss,
//     BellyDrum,
//     SludgeBomb,
//     MudSlap,
//     Octazooka,
//     Spikes,
//     ZapCannon,
//     Foresight,
//     DestinyBond,
//     PerishSong,
//     IcyWind,
//     Detect,
//     BoneRush,
//     LockOn,
//     Outrage,
//     Sandstorm,
//     GigaDrain,
//     Endure,
//     Charm,
//     Rollout,
//     FalseSwipe,
//     Swagger,
//     MilkDrink,
//     Spark,
//     FuryCutter,
//     SteelWing,
//     MeanLook,
//     Attract,
//     SleepTalk,
//     HealBell,
//     Return,
//     Present,
//     Frustration,
//     Safeguard,
//     PainSplit,
//     SacredFire,
//     Magnitude,
//     DynamicPunch,
//     Megahorn,
//     DragonBreath,
//     BatonPass,
//     Encore,
//     Pursuit,
//     RapidSpin,
//     SweetScent,
//     IronTail,
//     MetalClaw,
//     VitalThrow,
//     MorningSun,
//     Synthesis,
//     Moonlight,
//     HiddenPower,
//     CrossChop,
//     Twister,
//     RainDance,
//     SunnyDay,
//     Crunch,
//     MirrorCoat,
//     PsychUp,
//     ExtremeSpeed,
//     AncientPower,
//     ShadowBall,
//     FutureSight,
//     RockSmash,
//     Whirlpool,
//     BeatUp,
//     FakeOut,
//     Uproar,
//     Stockpile,
//     SpitUp,
//     Swallow,
//     HeatWave,
//     Hail,
//     Torment,
//     Flatter,
//     WillOWisp,
//     Memento,
//     Facade,
//     FocusPunch,
//     SmellingSalts,
//     FollowMe,
//     NaturePower,
//     Charge,
//     Taunt,
//     HelpingHand,
//     Trick,
//     RolePlay,
//     Wish,
//     Assist,
//     Ingrain,
//     Superpower,
//     MagicCoat,
//     Recycle,
//     Revenge,
//     BrickBreak,
//     Yawn,
//     KnockOff,
//     Endeavor,
//     Eruption,
//     SkillSwap,
//     Imprison,
//     Refresh,
//     Grudge,
//     Snatch,
//     SecretPower,
//     Dive,
//     ArmThrust,
//     Camouflage,
//     TailGlow,
//     LusterPurge,
//     MistBall,
//     FeatherDance,
//     TeeterDance,
//     BlazeKick,
//     MudSport,
//     IceBall,
//     NeedleArm,
//     SlackOff,
//     HyperVoice,
//     PoisonFang,
//     CrushClaw,
//     BlastBurn,
//     HydroCannon,
//     MeteorMash,
//     Astonish,
//     WeatherBall,
//     Aromatherapy,
//     FakeTears,
//     AirCutter,
//     Overheat,
//     OdorSleuth,
//     RockTomb,
//     SilverWind,
//     MetalSound,
//     GrassWhistle,
//     Tickle,
//     CosmicPower,
//     WaterSpout,
//     SignalBeam,
//     ShadowPunch,
//     Extrasensory,
//     SkyUppercut,
//     SandTomb,
//     SheerCold,
//     MuddyWater,
//     BulletSeed,
//     AerialAce,
//     IcicleSpear,
//     IronDefense,
//     Block,
//     Howl,
//     DragonClaw,
//     FrenzyPlant,
//     BulkUp,
//     Bounce,
//     MudShot,
//     PoisonTail,
//     Covet,
//     VoltTackle,
//     MagicalLeaf,
//     WaterSport,
//     CalmMind,
//     LeafBlade,
//     DragonDance,
//     RockBlast,
//     ShockWave,
//     WaterPulse,
//     DoomDesire,
//     PsychoBoost,
//     Roost,
//     Gravity,
//     MiracleEye,
//     WakeUpSlap,
//     HammerArm,
//     GyroBall,
//     HealingWish,
//     Brine,
//     NaturalGift,
//     Feint,
//     Pluck,
//     Tailwind,
//     Acupressure,
//     MetalBurst,
//     UTurn,
//     CloseCombat,
//     Payback,
//     Assurance,
//     Embargo,
//     Fling,
//     PsychoShift,
//     TrumpCard,
//     HealBlock,
//     WringOut,
//     PowerTrick,
//     GastroAcid,
//     LuckyChant,
//     MeFirst,
//     Copycat,
//     PowerSwap,
//     GuardSwap,
//     Punishment,
//     LastResort,
//     WorrySeed,
//     SuckerPunch,
//     ToxicSpikes,
//     HeartSwap,
//     AquaRing,
//     MagnetRise,
//     FlareBlitz,
//     ForcePalm,
//     AuraSphere,
//     RockPolish,
//     PoisonJab,
//     DarkPulse,
//     NightSlash,
//     AquaTail,
//     SeedBomb,
//     AirSlash,
//     XScissor,
//     BugBuzz,
//     DragonPulse,
//     DragonRush,
//     PowerGem,
//     DrainPunch,
//     VacuumWave,
//     FocusBlast,
//     EnergyBall,
//     BraveBird,
//     EarthPower,
//     Switcheroo,
//     GigaImpact,
//     NastyPlot,
//     BulletPunch,
//     Avalanche,
//     IceShard,
//     ShadowClaw,
//     ThunderFang,
//     IceFang,
//     FireFang,
//     ShadowSneak,
//     MudBomb,
//     PsychoCut,
//     ZenHeadbutt,
//     MirrorShot,
//     FlashCannon,
//     RockClimb,
//     Defog,
//     TrickRoom,
//     DracoMeteor,
//     Discharge,
//     LavaPlume,
//     LeafStorm,
//     PowerWhip,
//     RockWrecker,
//     CrossPoison,
//     GunkShot,
//     IronHead,
//     MagnetBomb,
//     StoneEdge,
//     Captivate,
//     StealthRock,
//     GrassKnot,
//     Chatter,
//     Judgment,
//     BugBite,
//     ChargeBeam,
//     WoodHammer,
//     AquaJet,
//     AttackOrder,
//     DefendOrder,
//     HealOrder,
//     HeadSmash,
//     DoubleHit,
//     RoarOfTime,
//     SpacialRend,
//     LunarDance,
//     CrushGrip,
//     MagmaStorm,
//     DarkVoid,
//     SeedFlare,
//     OminousWind,
//     ShadowForce,
//     HoneClaws,
//     WideGuard,
//     GuardSplit,
//     PowerSplit,
//     WonderRoom,
//     Psyshock,
//     Venoshock,
//     Autotomize,
//     RagePowder,
//     Telekinesis,
//     MagicRoom,
//     SmackDown,
//     StormThrow,
//     FlameBurst,
//     SludgeWave,
//     QuiverDance,
//     HeavySlam,
//     Synchronoise,
//     ElectroBall,
//     Soak,
//     FlameCharge,
//     Coil,
//     LowSweep,
//     AcidSpray,
//     FoulPlay,
//     SimpleBeam,
//     Entrainment,
//     AfterYou,
//     Round,
//     EchoedVoice,
//     ChipAway,
//     ClearSmog,
//     StoredPower,
//     QuickGuard,
//     AllySwitch,
//     Scald,
//     ShellSmash,
//     HealPulse,
//     Hex,
//     SkyDrop,
//     ShiftGear,
//     CircleThrow,
//     Incinerate,
//     Quash,
//     Acrobatics,
//     ReflectType,
//     Retaliate,
//     FinalGambit,
//     Bestow,
//     Inferno,
//     WaterPledge,
//     FirePledge,
//     GrassPledge,
//     VoltSwitch,
//     StruggleBug,
//     Bulldoze,
//     FrostBreath,
//     DragonTail,
//     WorkUp,
//     Electroweb,
//     WildCharge,
//     DrillRun,
//     DualChop,
//     HeartStamp,
//     HornLeech,
//     SacredSword,
//     RazorShell,
//     HeatCrash,
//     LeafTornado,
//     Steamroller,
//     CottonGuard,
//     NightDaze,
//     Psystrike,
//     TailSlap,
//     Hurricane,
//     HeadCharge,
//     GearGrind,
//     SearingShot,
//     TechnoBlast,
//     RelicSong,
//     SecretSword,
//     Glaciate,
//     BoltStrike,
//     BlueFlare,
//     FieryDance,
//     FreezeShock,
//     IceBurn,
//     Snarl,
//     IcicleCrash,
//     VCreate,
//     FusionFlare,
//     FusionBolt,
//     FlyingPress,
//     MatBlock,
//     Belch,
//     Rototiller,
//     StickyWeb,
//     FellStinger,
//     PhantomForce,
//     TrickOrTreat,
//     NobleRoar,
//     IonDeluge,
//     ParabolicCharge,
//     ForestsCurse,
//     PetalBlizzard,
//     FreezeDry,
//     DisarmingVoice,
//     PartingShot,
//     TopsyTurvy,
//     DrainingKiss,
//     CraftyShield,
//     FlowerShield,
//     GrassyTerrain,
//     MistyTerrain,
//     Electrify,
//     PlayRough,
//     FairyWind,
//     Moonblast,
//     Boomburst,
//     FairyLock,
//     KingsShield,
//     PlayNice,
//     Confide,
//     DiamondStorm,
//     SteamEruption,
//     HyperspaceHole,
//     WaterShuriken,
//     MysticalFire,
//     SpikyShield,
//     AromaticMist,
//     EerieImpulse,
//     VenomDrench,
//     Powder,
//     Geomancy,
//     MagneticFlux,
//     HappyHour,
//     ElectricTerrain,
//     DazzlingGleam,
//     Celebrate,
//     HoldHands,
//     BabyDollEyes,
//     Nuzzle,
//     HoldBack,
//     Infestation,
//     PowerUpPunch,
//     OblivionWing,
//     ThousandArrows,
//     ThousandWaves,
//     LandsWrath,
//     LightOfRuin,
//     OriginPulse,
//     PrecipiceBlades,
//     DragonAscent,
//     HyperspaceFury,
//     BreakneckBlitzPhysical,
//     BreakneckBlitzSpecial,
//     AllOutPummelingPhysical,
//     AllOutPummelingSpecial,
//     SupersonicSkystrikePhysical,
//     SupersonicSkystrikeSpecial,
//     AcidDownpourPhysical,
//     AcidDownpourSpecial,
//     TectonicRagePhysical,
//     TectonicRageSpecial,
//     ContinentalCrushPhysical,
//     ContinentalCrushSpecial,
//     SavageSpinOutPhysical,
//     SavageSpinOutSpecial,
//     NeverEndingNightmarePhysical,
//     NeverEndingNightmareSpecial,
//     CorkscrewCrashPhysical,
//     CorkscrewCrashSpecial,
//     InfernoOverdrivePhysical,
//     InfernoOverdriveSpecial,
//     HydroVortexPhysical,
//     HydroVortexSpecial,
//     BloomDoomPhysical,
//     BloomDoomSpecial,
//     GigavoltHavocPhysical,
//     GigavoltHavocSpecial,
//     ShatteredPsychePhysical,
//     ShatteredPsycheSpecial,
//     SubzeroSlammerPhysical,
//     SubzeroSlammerSpecial,
//     DevastatingDrakePhysical,
//     DevastatingDrakeSpecial,
//     BlackHoleEclipsePhysical,
//     BlackHoleEclipseSpecial,
//     TwinkleTacklePhysical,
//     TwinkleTackleSpecial,
//     Catastropika,
//     ShoreUp,
//     FirstImpression,
//     BanefulBunker,
//     SpiritShackle,
//     DarkestLariat,
//     SparklingAria,
//     IceHammer,
//     FloralHealing,
//     HighHorsepower,
//     StrengthSap,
//     SolarBlade,
//     Leafage,
//     Spotlight,
//     ToxicThread,
//     LaserFocus,
//     GearUp,
//     ThroatChop,
//     PollenPuff,
//     AnchorShot,
//     PsychicTerrain,
//     Lunge,
//     FireLash,
//     PowerTrip,
//     BurnUp,
//     SpeedSwap,
//     SmartStrike,
//     Purify,
//     RevelationDance,
//     CoreEnforcer,
//     TropKick,
//     Instruct,
//     BeakBlast,
//     ClangingScales,
//     DragonHammer,
//     BrutalSwing,
//     AuroraVeil,
//     SinisterArrowRaid,
//     MaliciousMoonsault,
//     OceanicOperetta,
//     GuardianOfAlola,
//     SoulStealing7StarStrike,
//     StokedSparksurfer,
//     PulverizingPancake,
//     ExtremeEvoboost,
//     GenesisSupernova,
//     ShellTrap,
//     FleurCannon,
//     PsychicFangs,
//     StompingTantrum,
//     ShadowBone,
//     Accelerock,
//     Liquidation,
//     PrismaticLaser,
//     SpectralThief,
//     SunsteelStrike,
//     MoongeistBeam,
//     TearfulLook,
//     ZingZap,
//     NaturesMadness,
//     MultiAttack,
//     TenMillionVoltThunderbolt,
//     MindBlown,
//     PlasmaFists,
//     PhotonGeyser,
//     LightThatBurnsTheSky,
//     SearingSunrazeSmash,
//     MenacingMoonrazeMaelstrom,
//     LetsSnuggleForever,
//     SplinteredStormshards,
//     ClangorousSoulblaze,
//     ZippyZap,
//     SplishySplash,
//     FloatyFall,
//     PikaPapow,
//     BouncyBubble,
//     BuzzyBuzz,
//     SizzlySlide,
//     GlitzyGlow,
//     BaddyBad,
//     SappySeed,
//     FreezyFrost,
//     SparklySwirl,
//     VeeveeVolley,
//     DoubleIronBash,
//     MaxGuard,
//     DynamaxCannon,
//     SnipeShot,
//     JawLock,
//     StuffCheeks,
//     NoRetreat,
//     TarShot,
//     MagicPowder,
//     DragonDarts,
//     Teatime,
//     Octolock,
//     BoltBeak,
//     FishiousRend,
//     CourtChange,
//     MaxFlare,
//     MaxFlutterby,
//     MaxLightning,
//     MaxStrike,
//     MaxKnuckle,
//     MaxPhantasm,
//     MaxHailstorm,
//     MaxOoze,
//     MaxGeyser,
//     MaxAirstream,
//     MaxStarfall,
//     MaxWyrmwind,
//     MaxMindstorm,
//     MaxRockfall,
//     MaxQuake,
//     MaxDarkness,
//     MaxOvergrowth,
//     MaxSteelspike,
//     ClangorousSoul,
//     BodyPress,
//     Decorate,
//     DrumBeating,
//     SnapTrap,
//     PyroBall,
//     BehemothBlade,
//     BehemothBash,
//     AuraWheel,
//     BreakingSwipe,
//     BranchPoke,
//     Overdrive,
//     AppleAcid,
//     GravApple,
//     SpiritBreak,
//     StrangeSteam,
//     LifeDew,
//     Obstruct,
//     FalseSurrender,
//     MeteorAssault,
//     Eternabeam,
//     SteelBeam,
//     ExpandingForce,
//     SteelRoller,
//     ScaleShot,
//     MeteorBeam,
//     ShellSideArm,
//     MistyExplosion,
//     GrassyGlide,
//     RisingVoltage,
//     TerrainPulse,
//     SkitterSmack,
//     BurningJealousy,
//     LashOut,
//     Poltergeist,
//     CorrosiveGas,
//     Coaching,
//     FlipTurn,
//     TripleAxel,
//     DualWingbeat,
//     ScorchingSands,
//     JungleHealing,
//     WickedBlow,
//     SurgingStrikes,
//     ThunderCage,
//     DragonEnergy,
//     FreezingGlare,
//     FieryWrath,
//     ThunderousKick,
//     GlacialLance,
//     AstralBarrage,
//     EerieSpell,
//     DireClaw,
//     PsyshieldBash,
//     PowerShift,
//     StoneAxe,
//     SpringtideStorm,
//     MysticalPower,
//     RagingFury,
//     WaveCrash,
//     Chloroblast,
//     MountainGale,
//     VictoryDance,
//     HeadlongRush,
//     BarbBarrage,
//     EsperWing,
//     BitterMalice,
//     Shelter,
//     TripleArrows,
//     InfernalParade,
//     CeaselessEdge,
//     BleakwindStorm,
//     WildboltStorm,
//     SandsearStorm,
//     LunarBlessing,
//     TakeHeart,
//     TeraBlast,
//     SilkTrap,
//     AxeKick,
//     LastRespects,
//     LuminaCrash,
//     OrderUp,
//     JetPunch,
//     SpicyExtract,
//     SpinOut,
//     PopulationBomb,
//     IceSpinner,
//     GlaiveRush,
//     RevivalBlessing,
//     SaltCure,
//     TripleDive,
//     MortalSpin,
//     Doodle,
//     FilletAway,
//     KowtowCleave,
//     FlowerTrick,
//     TorchSong,
//     AquaStep,
//     RagingBull,
//     MakeItRain,
//     Psyblade,
//     HydroSteam,
//     Ruination,
//     CollisionCourse,
//     ElectroDrift,
//     ShedTail,
//     ChillyReception,
//     TidyUp,
//     Snowscape,
//     Pounce,
//     Trailblaze,
//     ChillingWater,
//     HyperDrill,
//     TwinBeam,
//     RageFist,
//     ArmorCannon,
//     BitterBlade,
//     DoubleShock,
//     GigatonHammer,
//     Comeuppance,
//     AquaCutter,
//     BlazingTorque,
//     WickedTorque,
//     NoxiousTorque,
//     CombatTorque,
//     MagicalTorque,
//     BloodMoon,
//     MatchaGotcha,
//     SyrupBomb,
//     IvyCudgel,
//     ElectroShot,
//     TeraStarstorm,
//     FickleBeam,
//     BurningBulwark,
//     Thunderclap,
//     MightyCleave,
//     TachyonCutter,
//     HardPress,
//     DragonCheer,
//     AlluringVoice,
//     TemperFlare,
//     SupercellSlam,
//     PsychicNoise,
//     UpperHand,
//     MalignantChain,
//     ShadowRush = 10001,
//     ShadowBlast,
//     ShadowBlitz,
//     ShadowBolt,
//     ShadowBreak,
//     ShadowChill,
//     ShadowEnd,
//     ShadowFire,
//     ShadowRave,
//     ShadowStorm,
//     ShadowWave,
//     ShadowDown,
//     ShadowHalf,
//     ShadowHold,
//     ShadowMist,
//     ShadowPanic,
//     ShadowShed,
//     ShadowSky,
// }

#[repr(u16)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Ability {
    None = 0,
    Stench,
    Drizzle,
    SpeedBoost,
    BattleArmor,
    Sturdy,
    Damp,
    Limber,
    SandVeil,
    Static,
    VoltAbsorb,
    WaterAbsorb,
    Oblivious,
    CloudNine,
    CompoundEyes,
    Insomnia,
    ColorChange,
    Immunity,
    FlashFire,
    ShieldDust,
    OwnTempo,
    SuctionCups,
    Intimidate,
    ShadowTag,
    RoughSkin,
    WonderGuard,
    Levitate,
    EffectSpore,
    Synchronize,
    ClearBody,
    NaturalCure,
    LightningRod,
    SereneGrace,
    SwiftSwim,
    Chlorophyll,
    Illuminate,
    Trace,
    HugePower,
    PoisonPoint,
    InnerFocus,
    MagmaArmor,
    WaterVeil,
    MagnetPull,
    Soundproof,
    RainDish,
    SandStream,
    Pressure,
    ThickFat,
    EarlyBird,
    FlameBody,
    RunAway,
    KeenEye,
    HyperCutter,
    Pickup,
    Truant,
    Hustle,
    CuteCharm,
    Plus,
    Minus,
    Forecast,
    StickyHold,
    ShedSkin,
    Guts,
    MarvelScale,
    LiquidOoze,
    Overgrow,
    Blaze,
    Torrent,
    Swarm,
    RockHead,
    Drought,
    ArenaTrap,
    VitalSpirit,
    WhiteSmoke,
    PurePower,
    ShellArmor,
    AirLock,
    TangledFeet,
    MotorDrive,
    Rivalry,
    Steadfast,
    SnowCloak,
    Gluttony,
    AngerPoint,
    Unburden,
    Heatproof,
    Simple,
    DrySkin,
    Download,
    IronFist,
    PoisonHeal,
    Adaptability,
    SkillLink,
    Hydration,
    SolarPower,
    QuickFeet,
    Normalize,
    Sniper,
    MagicGuard,
    NoGuard,
    Stall,
    Technician,
    LeafGuard,
    Klutz,
    MoldBreaker,
    SuperLuck,
    Aftermath,
    Anticipation,
    Forewarn,
    Unaware,
    TintedLens,
    Filter,
    SlowStart,
    Scrappy,
    StormDrain,
    IceBody,
    SolidRock,
    SnowWarning,
    HoneyGather,
    Frisk,
    Reckless,
    Multitype,
    FlowerGift,
    BadDreams,
    Pickpocket,
    SheerForce,
    Contrary,
    Unnerve,
    Defiant,
    Defeatist,
    CursedBody,
    Healer,
    FriendGuard,
    WeakArmor,
    HeavyMetal,
    LightMetal,
    Multiscale,
    ToxicBoost,
    FlareBoost,
    Harvest,
    Telepathy,
    Moody,
    Overcoat,
    PoisonTouch,
    Regenerator,
    BigPecks,
    SandRush,
    WonderSkin,
    Analytic,
    Illusion,
    Imposter,
    Infiltrator,
    Mummy,
    Moxie,
    Justified,
    Rattled,
    MagicBounce,
    SapSipper,
    Prankster,
    SandForce,
    IronBarbs,
    ZenMode,
    VictoryStar,
    Turboblaze,
    Teravolt,
    AromaVeil,
    FlowerVeil,
    CheekPouch,
    Protean,
    FurCoat,
    Magician,
    Bulletproof,
    Competitive,
    StrongJaw,
    Refrigerate,
    SweetVeil,
    StanceChange,
    GaleWings,
    MegaLauncher,
    GrassPelt,
    Symbiosis,
    ToughClaws,
    Pixilate,
    Gooey,
    Aerilate,
    ParentalBond,
    DarkAura,
    FairyAura,
    AuraBreak,
    PrimordialSea,
    DesolateLand,
    DeltaStream,
    Stamina,
    WimpOut,
    EmergencyExit,
    WaterCompaction,
    Merciless,
    ShieldsDown,
    Stakeout,
    WaterBubble,
    Steelworker,
    Berserk,
    SlushRush,
    LongReach,
    LiquidVoice,
    Triage,
    Galvanize,
    SurgeSurfer,
    Schooling,
    Disguise,
    BattleBond,
    PowerConstruct,
    Corrosion,
    Comatose,
    QueenlyMajesty,
    InnardsOut,
    Dancer,
    Battery,
    Fluffy,
    Dazzling,
    SoulHeart,
    TanglingHair,
    Receiver,
    PowerOfAlchemy,
    BeastBoost,
    RksSystem,
    ElectricSurge,
    PsychicSurge,
    MistySurge,
    GrassySurge,
    FullMetalBody,
    ShadowShield,
    PrismArmor,
    Neuroforce,
    IntrepidSword,
    DauntlessShield,
    Libero,
    BallFetch,
    CottonDown,
    PropellerTail,
    MirrorArmor,
    GulpMissile,
    Stalwart,
    SteamEngine,
    PunkRock,
    SandSpit,
    IceScales,
    Ripen,
    IceFace,
    PowerSpot,
    Mimicry,
    ScreenCleaner,
    SteelySpirit,
    PerishBody,
    WanderingSpirit,
    GorillaTactics,
    NeutralizingGas,
    PastelVeil,
    HungerSwitch,
    QuickDraw,
    UnseenFist,
    CuriousMedicine,
    Transistor,
    DragonsMaw,
    ChillingNeigh,
    GrimNeigh,
    AsOneGlastrier,
    AsOneSpectrier,
    LingeringAroma,
    SeedSower,
    ThermalExchange,
    AngerShell,
    PurifyingSalt,
    WellBakedBody,
    WindRider,
    GuardDog,
    RockyPayload,
    WindPower,
    ZeroToHero,
    Commander,
    Electromorphosis,
    Protosynthesis,
    QuarkDrive,
    GoodAsGold,
    VesselOfRuin,
    SwordOfRuin,
    TabletsOfRuin,
    BeadsOfRuin,
    OrichalcumPulse,
    HadronEngine,
    Opportunist,
    CudChew,
    Sharpness,
    SupremeOverlord,
    Costar,
    ToxicDebris,
    ArmorTail,
    EarthEater,
    MyceliumMight,
    MindsEye,
    SupersweetSyrup,
    Hospitality,
    ToxicChain,
    EmbodyAspect,
    TeraShift,
    TeraShell,
    TeraformZero,
    PoisonPuppeteer,
    Mountaineer = 10001,
    WaveRider,
    Skater,
    Thrust,
    Perception,
    Parry,
    Instinct,
    Dodge,
    JaggedEdge,
    Frostbite,
    Tenacity,
    Pride,
    DeepSleep,
    PowerNap,
    Spirit,
    WarmBlanket,
    Gulp,
    Herbivore,
    Sandpit,
    HotBlooded,
    Medic,
    LifeForce,
    Lunchbox,
    Nurse,
    Melee,
    Sponge,
    Bodyguard,
    Hero,
    LastBastion,
    Stealth,
    Vanguard,
    Nomad,
    Sequence,
    GrassCloak,
    Celebrate,
    Lullaby,
    Calming,
    Daze,
    Frighten,
    Interference,
    MoodMaker,
    Confidence,
    Fortune,
    Bonanza,
    Explode,
    Omnipotent,
    Share,
    BlackHole,
    ShadowDash,
    Sprint,
    Disgust,
    HighRise,
    Climber,
    FlameBoost,
    AquaBoost,
    RunUp,
    Conqueror,
    Shackle,
    Decoy,
    Shield
}

impl Ability {
    pub fn from_db_id(id: ID) -> Self {
        unsafe {std::mem::transmute(id)}
    }
}

#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Item {
    MasterBall = 1,
    UltraBall,
    GreatBall,
    PokeBall,
    SafariBall,
    NetBall,
    DiveBall,
    NestBall,
    RepeatBall,
    TimerBall,
    LuxuryBall,
    PremierBall,
    DuskBall,
    HealBall,
    QuickBall,
    CherishBall,
    Potion,
    Antidote,
    BurnHeal,
    IceHeal,
    Awakening,
    ParalyzeHeal,
    FullRestore,
    MaxPotion,
    HyperPotion,
    SuperPotion,
    FullHeal,
    Revive,
    MaxRevive,
    FreshWater,
    SodaPop,
    Lemonade,
    MoomooMilk,
    EnergyPowder,
    EnergyRoot,
    HealPowder,
    RevivalHerb,
    Ether,
    MaxEther,
    Elixir,
    MaxElixir,
    LavaCookie,
    BerryJuice,
    SacredAsh,
    HpUp,
    Protein,
    Iron,
    Carbos,
    Calcium,
    RareCandy,
    PpUp,
    Zinc,
    PpMax,
    OldGateau,
    GuardSpec,
    DireHit,
    XAttack,
    XDefense,
    XSpeed,
    XAccuracy,
    XSpAtk,
    XSpDef,
    PokeDoll,
    FluffyTail,
    BlueFlute,
    YellowFlute,
    RedFlute,
    BlackFlute,
    WhiteFlute,
    ShoalSalt,
    ShoalShell,
    RedShard,
    BlueShard,
    YellowShard,
    GreenShard,
    SuperRepel,
    MaxRepel,
    EscapeRope,
    Repel,
    SunStone,
    MoonStone,
    FireStone,
    ThunderStone,
    WaterStone,
    LeafStone,
    TinyMushroom,
    BigMushroom,
    Pearl,
    BigPearl,
    Stardust,
    StarPiece,
    Nugget,
    HeartScale,
    Honey,
    GrowthMulch,
    DampMulch,
    StableMulch,
    GooeyMulch,
    RootFossil,
    ClawFossil,
    HelixFossil,
    DomeFossil,
    OldAmber,
    ArmorFossil,
    SkullFossil,
    RareBone,
    ShinyStone,
    DuskStone,
    DawnStone,
    OvalStone,
    OddKeystone,
    AdamantOrb,
    LustrousOrb,
    GrassMail,
    FlameMail,
    BubbleMail,
    BloomMail,
    TunnelMail,
    SteelMail,
    HeartMail,
    SnowMail,
    SpaceMail,
    AirMail,
    MosaicMail,
    BrickMail,
    CheriBerry,
    ChestoBerry,
    PechaBerry,
    RawstBerry,
    AspearBerry,
    LeppaBerry,
    OranBerry,
    PersimBerry,
    LumBerry,
    SitrusBerry,
    FigyBerry,
    WikiBerry,
    MagoBerry,
    AguavBerry,
    IapapaBerry,
    RazzBerry,
    BlukBerry,
    NanabBerry,
    WepearBerry,
    PinapBerry,
    PomegBerry,
    KelpsyBerry,
    QualotBerry,
    HondewBerry,
    GrepaBerry,
    TamatoBerry,
    CornnBerry,
    MagostBerry,
    RabutaBerry,
    NomelBerry,
    SpelonBerry,
    PamtreBerry,
    WatmelBerry,
    DurinBerry,
    BelueBerry,
    OccaBerry,
    PasshoBerry,
    WacanBerry,
    RindoBerry,
    YacheBerry,
    ChopleBerry,
    KebiaBerry,
    ShucaBerry,
    CobaBerry,
    PayapaBerry,
    TangaBerry,
    ChartiBerry,
    KasibBerry,
    HabanBerry,
    ColburBerry,
    BabiriBerry,
    ChilanBerry,
    LiechiBerry,
    GanlonBerry,
    SalacBerry,
    PetayaBerry,
    ApicotBerry,
    LansatBerry,
    StarfBerry,
    EnigmaBerry,
    MicleBerry,
    CustapBerry,
    JabocaBerry,
    RowapBerry,
    BrightPowder,
    WhiteHerb,
    MachoBrace,
    ExpShare,
    QuickClaw,
    SootheBell,
    MentalHerb,
    ChoiceBand,
    KingsRock,
    SilverPowder,
    AmuletCoin,
    CleanseTag,
    SoulDew,
    DeepSeaTooth,
    DeepSeaScale,
    SmokeBall,
    Everstone,
    FocusBand,
    LuckyEgg,
    ScopeLens,
    MetalCoat,
    Leftovers,
    DragonScale,
    LightBall,
    SoftSand,
    HardStone,
    MiracleSeed,
    BlackGlasses,
    BlackBelt,
    Magnet,
    MysticWater,
    SharpBeak,
    PoisonBarb,
    NeverMeltIce,
    SpellTag,
    TwistedSpoon,
    Charcoal,
    DragonFang,
    SilkScarf,
    UpGrade,
    ShellBell,
    SeaIncense,
    LaxIncense,
    LuckyPunch,
    MetalPowder,
    ThickClub,
    Stick,
    RedScarf,
    BlueScarf,
    PinkScarf,
    GreenScarf,
    YellowScarf,
    WideLens,
    MuscleBand,
    WiseGlasses,
    ExpertBelt,
    LightClay,
    LifeOrb,
    PowerHerb,
    ToxicOrb,
    FlameOrb,
    QuickPowder,
    FocusSash,
    ZoomLens,
    Metronome,
    IronBall,
    LaggingTail,
    DestinyKnot,
    BlackSludge,
    IcyRock,
    SmoothRock,
    HeatRock,
    DampRock,
    GripClaw,
    ChoiceScarf,
    StickyBarb,
    PowerBracer,
    PowerBelt,
    PowerLens,
    PowerBand,
    PowerAnklet,
    PowerWeight,
    ShedShell,
    BigRoot,
    ChoiceSpecs,
    FlamePlate,
    SplashPlate,
    ZapPlate,
    MeadowPlate,
    IciclePlate,
    FistPlate,
    ToxicPlate,
    EarthPlate,
    SkyPlate,
    MindPlate,
    InsectPlate,
    StonePlate,
    SpookyPlate,
    DracoPlate,
    DreadPlate,
    IronPlate,
    OddIncense,
    RockIncense,
    FullIncense,
    WaveIncense,
    RoseIncense,
    LuckIncense,
    PureIncense,
    Protector,
    Electirizer,
    Magmarizer,
    DubiousDisc,
    ReaperCloth,
    RazorClaw,
    RazorFang,
    Tm01,
    Tm02,
    Tm03,
    Tm04,
    Tm05,
    Tm06,
    Tm07,
    Tm08,
    Tm09,
    Tm10,
    Tm11,
    Tm12,
    Tm13,
    Tm14,
    Tm15,
    Tm16,
    Tm17,
    Tm18,
    Tm19,
    Tm20,
    Tm21,
    Tm22,
    Tm23,
    Tm24,
    Tm25,
    Tm26,
    Tm27,
    Tm28,
    Tm29,
    Tm30,
    Tm31,
    Tm32,
    Tm33,
    Tm34,
    Tm35,
    Tm36,
    Tm37,
    Tm38,
    Tm39,
    Tm40,
    Tm41,
    Tm42,
    Tm43,
    Tm44,
    Tm45,
    Tm46,
    Tm47,
    Tm48,
    Tm49,
    Tm50,
    Tm51,
    Tm52,
    Tm53,
    Tm54,
    Tm55,
    Tm56,
    Tm57,
    Tm58,
    Tm59,
    Tm60,
    Tm61,
    Tm62,
    Tm63,
    Tm64,
    Tm65,
    Tm66,
    Tm67,
    Tm68,
    Tm69,
    Tm70,
    Tm71,
    Tm72,
    Tm73,
    Tm74,
    Tm75,
    Tm76,
    Tm77,
    Tm78,
    Tm79,
    Tm80,
    Tm81,
    Tm82,
    Tm83,
    Tm84,
    Tm85,
    Tm86,
    Tm87,
    Tm88,
    Tm89,
    Tm90,
    Tm91,
    Tm92,
    Hm01,
    Hm02,
    Hm03,
    Hm04,
    Hm05,
    Hm06,
    Hm07,
    Hm08,
    ExplorerKit,
    LootSack,
    RuleBook,
    PokeRadar,
    PointCard,
    Journal,
    SealCase,
    FashionCase,
    SealBag,
    PalPad,
    WorksKey,
    OldCharm,
    GalacticKey,
    RedChain,
    TownMap,
    VsSeeker,
    CoinCase,
    OldRod,
    GoodRod,
    SuperRod,
    Sprayduck,
    PoffinCase,
    Bicycle,
    SuiteKey,
    OaksLetter,
    LunarWing,
    MemberCard,
    AzureFlute,
    SsTicket,
    ContestPass,
    MagmaStone,
    Parcel,
    Coupon1,
    Coupon2,
    Coupon3,
    StorageKey,
    SecretPotion,
    GriseousOrb,
    VsRecorder,
    Gracidea,
    SecretKey,
    ApricornBox,
    BerryPots,
    SquirtBottle,
    LureBall,
    LevelBall,
    MoonBall,
    HeavyBall,
    FastBall,
    FriendBall,
    LoveBall,
    ParkBall,
    SportBall,
    RedApricorn,
    BlueApricorn,
    YellowApricorn,
    GreenApricorn,
    PinkApricorn,
    WhiteApricorn,
    BlackApricorn,
    DowsingMachine,
    RageCandyBar,
    RedOrb,
    BlueOrb,
    JadeOrb,
    EnigmaStone,
    UnownReport,
    BlueCard,
    SlowpokeTail,
    ClearBell,
    CardKey,
    BasementKey,
    RedScale,
    LostItem,
    Pass,
    MachinePart,
    SilverWing,
    RainbowWing,
    MysteryEgg,
    GbSounds,
    TidalBell,
    DataCard01,
    DataCard02,
    DataCard03,
    DataCard04,
    DataCard05,
    DataCard06,
    DataCard07,
    DataCard08,
    DataCard09,
    DataCard10,
    DataCard11,
    DataCard12,
    DataCard13,
    DataCard14,
    DataCard15,
    DataCard16,
    DataCard17,
    DataCard18,
    DataCard19,
    DataCard20,
    DataCard21,
    DataCard22,
    DataCard23,
    DataCard24,
    DataCard25,
    DataCard26,
    DataCard27,
    LockCapsule,
    PhotoAlbum,
    OrangeMail,
    HarborMail,
    GlitterMail,
    MechMail,
    WoodMail,
    WaveMail,
    BeadMail,
    ShadowMail,
    TropicMail,
    DreamMail,
    FabMail,
    RetroMail,
    MachBike,
    AcroBike,
    WailmerPail,
    DevonGoods,
    SootSack,
    PokeblockCase,
    Letter,
    EonTicket,
    Scanner,
    GoGoggles,
    Meteorite,
    Rm1Key,
    Rm2Key,
    Rm4Key,
    Rm6Key,
    DevonScope,
    OaksParcel,
    PokeFlute,
    BikeVoucher,
    GoldTeeth,
    LiftKey,
    SilphScope,
    FameChecker,
    TmCase,
    BerryPouch,
    TeachyTv,
    TriPass,
    RainbowPass,
    Tea,
    Mysticticket,
    Auroraticket,
    PowderJar,
    Ruby,
    Sapphire,
    MagmaEmblem,
    OldSeaMap,
    DouseDrive,
    ShockDrive,
    BurnDrive,
    ChillDrive,
    SweetHeart,
    GreetMail,
    FavoredMail,
    RsvpMail,
    ThanksMail,
    InquiryMail,
    LikeMail,
    ReplyMail,
    BridgeMailS,
    BridgeMailD,
    BridgeMailT,
    BridgeMailV,
    BridgeMailM,
    PrismScale,
    Eviolite,
    FloatStone,
    RockyHelmet,
    AirBalloon,
    RedCard,
    RingTarget,
    BindingBand,
    AbsorbBulb,
    CellBattery,
    EjectButton,
    FireGem,
    WaterGem,
    ElectricGem,
    GrassGem,
    IceGem,
    FightingGem,
    PoisonGem,
    GroundGem,
    FlyingGem,
    PsychicGem,
    BugGem,
    RockGem,
    GhostGem,
    DarkGem,
    SteelGem,
    HealthWing,
    MuscleWing,
    ResistWing,
    GeniusWing,
    CleverWing,
    SwiftWing,
    PrettyWing,
    CoverFossil,
    PlumeFossil,
    LibertyPass,
    PassOrb,
    DreamBall,
    PokeToy,
    PropCase,
    DragonSkull,
    BalmMushroom,
    BigNugget,
    PearlString,
    CometShard,
    RelicCopper,
    RelicSilver,
    RelicGold,
    RelicVase,
    RelicBand,
    RelicStatue,
    RelicCrown,
    Casteliacone,
    DireHit2,
    XSpeed2,
    XSpAtk2,
    XSpDef2,
    XDefense2,
    XAttack2,
    XAccuracy2,
    XSpeed3,
    XSpAtk3,
    XSpDef3,
    XDefense3,
    XAttack3,
    XAccuracy3,
    XSpeed6,
    XSpAtk6,
    XSpDef6,
    XDefense6,
    XAttack6,
    XAccuracy6,
    AbilityUrge,
    ItemDrop,
    ItemUrge,
    ResetUrge,
    DireHit3,
    LightStone,
    DarkStone,
    Tm93,
    Tm94,
    Tm95,
    Xtransceiver,
    GodStone,
    Gram1,
    Gram2,
    Gram3,
    DragonGem = 668,
    NormalGem,
    MedalBox,
    DnaSplicers,
    Permit = 673,
    OvalCharm,
    ShinyCharm,
    PlasmaCard,
    GrubbyHanky,
    ColressMachine,
    DroppedItem,
    RevealGlass = 681,
    WeaknessPolicy,
    AssaultVest,
    PixiePlate,
    AbilityCapsule,
    WhippedDream,
    Sachet,
    LuminousMoss,
    Snowball,
    SafetyGoggles,
    RichMulch,
    SurpriseMulch,
    BoostMulch,
    AmazeMulch,
    Gengarite,
    Gardevoirite,
    Ampharosite,
    Venusaurite,
    CharizarditeX,
    Blastoisinite,
    MewtwoniteX,
    MewtwoniteY,
    Blazikenite,
    Medichamite,
    Houndoominite,
    Aggronite,
    Banettite,
    Tyranitarite,
    Scizorite,
    Pinsirite,
    Aerodactylite,
    Lucarionite,
    Abomasite,
    Kangaskhanite,
    Gyaradosite,
    Absolite,
    CharizarditeY,
    Alakazite,
    Heracronite,
    Mawilite,
    Manectite,
    Garchompite,
    RoseliBerry,
    KeeBerry,
    MarangaBerry,
    DiscountCoupon,
    StrangeSouvenir,
    LumioseGalette,
    JawFossil,
    SailFossil,
    FairyGem,
    AdventureRules,
    ElevatorKey,
    HoloCaster,
    HonorOfKalos,
    IntriguingStone,
    LensCase,
    LookerTicket,
    MegaRing,
    PowerPlantPass,
    ProfsLetter,
    RollerSkates,
    Sprinklotad,
    TmvPass,
    Tm96,
    Tm97,
    Tm98,
    Tm99,
    Tm100,
    Latiasite = 760,
    Latiosite,
    CommonStone,
    MakeupBag,
    TravelTrunk,
    ShalourSable,
    MegaCharm = 768,
    MegaGlove,
    DevonParts,
    PokeblockKit = 772,
    KeyToRoom1,
    KeyToRoom2,
    KeyToRoom4,
    KeyToRoom6,
    DevonScubaGear = 779,
    ContestCostumeJacket,
    MagmaSuit = 782,
    AquaSuit,
    PairOfTickets,
    MegaBracelet,
    MegaPendant,
    MegaGlasses,
    MegaAnchor,
    MegaStickpin,
    MegaTiara,
    MegaAnklet,
    Swampertite = 793,
    Sceptilite,
    Sablenite,
    Altarianite,
    Galladite,
    Audinite,
    Metagrossite,
    Sharpedonite,
    Slowbronite,
    Steelixite,
    Pidgeotite,
    Glalitite,
    Diancite,
    PrisonBottle,
    MegaCuff,
    Cameruptite,
    Lopunnite,
    Salamencite,
    Beedrillite,
    KeyStone = 814,
    MeteoriteShard,
    EonFlute,
    NormaliumZHeld,
    FiriumZHeld,
    WateriumZHeld,
    ElectriumZHeld,
    GrassiumZHeld,
    IciumZHeld,
    FightiniumZHeld,
    PoisoniumZHeld,
    GroundiumZHeld,
    FlyiniumZHeld,
    PsychiumZHeld,
    BuginiumZHeld,
    RockiumZHeld,
    GhostiumZHeld,
    DragoniumZHeld,
    DarkiniumZHeld,
    SteeliumZHeld,
    FairiumZHeld,
    PikaniumZHeld,
    BottleCap,
    GoldBottleCap,
    ZRing,
    DecidiumZHeld,
    InciniumZHeld,
    PrimariumZHeld,
    TapuniumZHeld,
    MarshadiumZHeld,
    AloraichiumZHeld,
    SnorliumZHeld,
    EeviumZHeld,
    MewniumZHeld,
    PikashuniumZHeld = 877,
    ForageBag,
    FishingRod,
    ProfessorsMask,
    FestivalTicket,
    SparklingStone,
    AdrenalineOrb,
    ZygardeCube,
    IceStone,
    RidePager,
    BeastBall,
    BigMalasada,
    RedNectar,
    YellowNectar,
    PinkNectar,
    PurpleNectar,
    SunFlute,
    MoonFlute,
    EnigmaticCard,
    TerrainExtender,
    ProtectivePads,
    ElectricSeed,
    PsychicSeed,
    MistySeed,
    GrassySeed,
    FightingMemory,
    FlyingMemory,
    PoisonMemory,
    GroundMemory,
    RockMemory,
    BugMemory,
    GhostMemory,
    SteelMemory,
    FireMemory,
    WaterMemory,
    GrassMemory,
    ElectricMemory,
    PsychicMemory,
    IceMemory,
    DragonMemory,
    DarkMemory,
    FairyMemory,
    BikeGreen,
    StorageKeyGalacticWarehouse,
    BasementKeyGoldenrod,
    XtransceiverRed,
    XtransceiverYellow,
    DnaSplicersMerge,
    DnaSplicersSplit,
    DroppedItemRed,
    DroppedItemYellow,
    HoloCasterGreen,
    BikeYellow,
    HoloCasterRed,
    BasementKeyNewMauville,
    StorageKeySeaMauville,
    SsTicketHoenn,
    ContestCostumeDress,
    Meteorite2,
    Meteorite3,
    Meteorite4,
    NormaliumZBag,
    FiriumZBag,
    WateriumZBag,
    ElectriumZBag,
    GrassiumZBag,
    IciumZBag,
    FightiniumZBag,
    PoisoniumZBag,
    GroundiumZBag,
    FlyiniumZBag,
    PsychiumZBag,
    BuginiumZBag,
    RockiumZBag,
    GhostiumZBag,
    DragoniumZBag,
    DarkiniumZBag,
    SteeliumZBag,
    FairiumZBag,
    PikaniumZBag,
    DecidiumZBag,
    InciniumZBag,
    PrimariumZBag,
    TapuniumZBag,
    MarshadiumZBag,
    AloraichiumZBag,
    SnorliumZBag,
    EeviumZBag,
    MewniumZBag,
    PikashuniumZBag,
    SolganiumZHeld,
    LunaliumZHeld,
    UltranecroziumZHeld,
    MimikiumZHeld,
    LycaniumZHeld,
    KommoniumZHeld,
    SolganiumZBag,
    LunaliumZBag,
    UltranecroziumZBag,
    MimikiumZBag,
    LycaniumZBag,
    KommoniumZBag,
    ZPowerRing,
    PinkPetal,
    OrangePetal,
    BluePetal,
    RedPetal,
    GreenPetal,
    YellowPetal,
    PurplePetal,
    RainbowFlower,
    SurgeBadge,
    NSolarizerMerge,
    NLunarizerMerge,
    NSolarizerSplit,
    NLunarizerSplit,
    IlimasNormaliumZ,
    LeftPokeBall,
    RotoHatch,
    RotoBargain,
    RotoPrizeMoney,
    RotoExpPoints,
    RotoFriendship,
    RotoEncounter,
    RotoStealth,
    RotoHpRestore,
    RotoPpRestore,
    RotoBoost,
    RotoCatch,
    Autograph,
    PokemonBox,
    MedicinePocket,
    CandyJar,
    PowerUpPocket,
    ClothingTrunk,
    CatchingPocket,
    BattlePocket,
    SilverRazzBerry,
    GoldenRazzBerry,
    SilverNanabBerry,
    GoldenNanabBerry,
    SilverPinapBerry,
    GoldenPinapBerry,
    SecretKeyLetsgo,
    SsTicketLetsgo,
    ParcelLetsgo,
    CardKeyLetsgo,
    StretchySpring,
    ChalkyStone,
    Marble,
    LoneEarring,
    BeachGlass,
    GoldLeaf,
    SilverLeaf,
    PolishedMudBall,
    TropicalShell,
    LeafLetterPikachu,
    LeafLetterEevee,
    SmallBouquet,
    Lure,
    SuperLure,
    MaxLure,
    PewterCrunchies,
    HealthCandy,
    MightyCandy,
    ToughCandy,
    SmartCandy,
    CourageCandy,
    QuickCandy,
    HealthCandyL,
    MightyCandyL,
    ToughCandyL,
    SmartCandyL,
    CourageCandyL,
    QuickCandyL,
    HealthCandyXl,
    MightyCandyXl,
    ToughCandyXl,
    SmartCandyXl,
    CourageCandyXl,
    QuickCandyXl,
    BulbasaurCandy,
    CharmanderCandy,
    SquirtleCandy,
    CaterpieCandy,
    WeedleCandy,
    PidgeyCandy,
    RattataCandy,
    SpearowCandy,
    EkansCandy,
    PikachuCandy,
    SandshrewCandy,
    NidoranFCandy,
    NidoranMCandy,
    ClefairyCandy,
    VulpixCandy,
    JigglypuffCandy,
    ZubatCandy,
    OddishCandy,
    ParasCandy,
    VenonatCandy,
    DiglettCandy,
    MeowthCandy,
    PsyduckCandy,
    MankeyCandy,
    GrowlitheCandy,
    PoliwagCandy,
    AbraCandy,
    MachopCandy,
    BellsproutCandy,
    TentacoolCandy,
    GeodudeCandy,
    PonytaCandy,
    SlowpokeCandy,
    MagnemiteCandy,
    FarfetchdCandy,
    DoduoCandy,
    SeelCandy,
    GrimerCandy,
    ShellderCandy,
    GastlyCandy,
    OnixCandy,
    DrowzeeCandy,
    KrabbyCandy,
    VoltorbCandy,
    ExeggcuteCandy,
    CuboneCandy,
    HitmonleeCandy,
    HitmonchanCandy,
    LickitungCandy,
    KoffingCandy,
    RhyhornCandy,
    ChanseyCandy,
    TangelaCandy,
    KangaskhanCandy,
    HorseaCandy,
    GoldeenCandy,
    StaryuCandy,
    MrMimeCandy,
    ScytherCandy,
    JynxCandy,
    ElectabuzzCandy,
    PinsirCandy,
    TaurosCandy,
    MagikarpCandy,
    LaprasCandy,
    DittoCandy,
    EeveeCandy,
    PorygonCandy,
    OmanyteCandy,
    KabutoCandy,
    AerodactylCandy,
    SnorlaxCandy,
    ArticunoCandy,
    ZapdosCandy,
    MoltresCandy,
    DratiniCandy,
    MewtwoCandy,
    MewCandy,
    MeltanCandy,
    MagmarCandy,
    Endorsement,
    PokemonBoxLink,
    WishingStar,
    DynamaxBand,
    FishingRodGalar,
    RotomBike,
    Sausages,
    BobsFoodTin,
    BachsFoodTin,
    TinOfBeans,
    Bread,
    Pasta,
    MixedMushrooms,
    SmokePokeTail,
    LargeLeek,
    FancyApple,
    BrittleBones,
    PackOfPotatoes,
    PungentRoot,
    SaladMix,
    FriedFood,
    BoiledEgg,
    CampingGear,
    RustedSword,
    RustedShield,
    FossilizedBird,
    FossilizedFish,
    FossilizedDrake,
    FossilizedDino,
    StrawberrySweet,
    LoveSweet,
    BerrySweet,
    CloverSweet,
    FlowerSweet,
    StarSweet,
    RibbonSweet,
    SweetApple,
    TartApple,
    ThroatSpray,
    EjectPack,
    HeavyDutyBoots,
    BlunderPolicy,
    RoomService,
    UtilityUmbrella,
    ExpCandyXs,
    ExpCandyS,
    ExpCandyM,
    ExpCandyL,
    ExpCandyXl,
    DynamaxCandy,
    Tr00,
    Tr01,
    Tr02,
    Tr03,
    Tr04,
    Tr05,
    Tr06,
    Tr07,
    Tr08,
    Tr09,
    Tr10,
    Tr11,
    Tr12,
    Tr13,
    Tr14,
    Tr15,
    Tr16,
    Tr17,
    Tr18,
    Tr19,
    Tr20,
    Tr21,
    Tr22,
    Tr23,
    Tr24,
    Tr25,
    Tr26,
    Tr27,
    Tr28,
    Tr29,
    Tr30,
    Tr31,
    Tr32,
    Tr33,
    Tr34,
    Tr35,
    Tr36,
    Tr37,
    Tr38,
    Tr39,
    Tr40,
    Tr41,
    Tr42,
    Tr43,
    Tr44,
    Tr45,
    Tr46,
    Tr47,
    Tr48,
    Tr49,
    Tr50,
    Tr51,
    Tr52,
    Tr53,
    Tr54,
    Tr55,
    Tr56,
    Tr57,
    Tr58,
    Tr59,
    Tr60,
    Tr61,
    Tr62,
    Tr63,
    Tr64,
    Tr65,
    Tr66,
    Tr67,
    Tr68,
    Tr69,
    Tr70,
    Tr71,
    Tr72,
    Tr73,
    Tr74,
    Tr75,
    Tr76,
    Tr77,
    Tr78,
    Tr79,
    Tr80,
    Tr81,
    Tr82,
    Tr83,
    Tr84,
    Tr85,
    Tr86,
    Tr87,
    Tr88,
    Tr89,
    Tr90,
    Tr91,
    Tr92,
    Tr93,
    Tr94,
    Tr95,
    Tr96,
    Tr97,
    Tr98,
    Tr99,
    Tm00,
    LonelyMint,
    AdamantMint,
    NaughtyMint,
    BraveMint,
    BoldMint,
    ImpishMint,
    LaxMint,
    RelaxedMint,
    ModestMint,
    MildMint,
    RashMint,
    QuietMint,
    CalmMint,
    GentleMint,
    CarefulMint,
    SassyMint,
    TimidMint,
    HastyMint,
    JollyMint,
    NaiveMint,
    SeriousMint,
    WishingPiece,
    CrackedPot,
    ChippedPot,
    HiTechEarbuds,
    FruitBunch,
    MoomooCheese,
    SpiceMix,
    FreshCream,
    PackagedCurry,
    CoconutMilk,
    InstantNoodles,
    PrecookedBurger,
    Gigantamix,
    WishingChip,
    RotomBikeWaterMode,
    CatchingCharm,
    OldLetter,
    BandAutograph,
    SoniasBook,
    RotomCatalog,
    DynamaxCrystalAnd458,
    DynamaxCrystalAnd15,
    DynamaxCrystalAnd337,
    DynamaxCrystalAnd603,
    DynamaxCrystalAnd390,
    DynamaxCrystalSgr6879,
    DynamaxCrystalSgr6859,
    DynamaxCrystalSgr6913,
    DynamaxCrystalSgr7348,
    DynamaxCrystalSgr7121,
    DynamaxCrystalSgr6746,
    DynamaxCrystalSgr7194,
    DynamaxCrystalSgr7337,
    DynamaxCrystalSgr7343,
    DynamaxCrystalSgr6812,
    DynamaxCrystalSgr7116,
    DynamaxCrystalSgr7264,
    DynamaxCrystalSgr7597,
    DynamaxCrystalDel7882,
    DynamaxCrystalDel7906,
    DynamaxCrystalDel7852,
    DynamaxCrystalPsc596,
    DynamaxCrystalPsc361,
    DynamaxCrystalPsc510,
    DynamaxCrystalPsc437,
    DynamaxCrystalPsc8773,
    DynamaxCrystalLep1865,
    DynamaxCrystalLep1829,
    DynamaxCrystalBoo5340,
    DynamaxCrystalBoo5506,
    DynamaxCrystalBoo5435,
    DynamaxCrystalBoo5602,
    DynamaxCrystalBoo5733,
    DynamaxCrystalBoo5235,
    DynamaxCrystalBoo5351,
    DynamaxCrystalHya3748,
    DynamaxCrystalHya3903,
    DynamaxCrystalHya3418,
    DynamaxCrystalHya3482,
    DynamaxCrystalHya3845,
    DynamaxCrystalEri1084,
    DynamaxCrystalEri472,
    DynamaxCrystalEri1666,
    DynamaxCrystalEri897,
    DynamaxCrystalEri1231,
    DynamaxCrystalEri874,
    DynamaxCrystalEri1298,
    DynamaxCrystalEri1325,
    DynamaxCrystalEri984,
    DynamaxCrystalEri1464,
    DynamaxCrystalEri1393,
    DynamaxCrystalEri850,
    DynamaxCrystalTau1409,
    DynamaxCrystalTau1457,
    DynamaxCrystalTau1165,
    DynamaxCrystalTau1791,
    DynamaxCrystalTau1910,
    DynamaxCrystalTau1346,
    DynamaxCrystalTau1373,
    DynamaxCrystalTau1412,
    DynamaxCrystalCma2491,
    DynamaxCrystalCma2693,
    DynamaxCrystalCma2294,
    DynamaxCrystalCma2827,
    DynamaxCrystalCma2282,
    DynamaxCrystalCma2618,
    DynamaxCrystalCma2657,
    DynamaxCrystalCma2646,
    DynamaxCrystalUma4905,
    DynamaxCrystalUma4301,
    DynamaxCrystalUma5191,
    DynamaxCrystalUma5054,
    DynamaxCrystalUma4295,
    DynamaxCrystalUma4660,
    DynamaxCrystalUma4554,
    DynamaxCrystalUma4069,
    DynamaxCrystalUma3569,
    DynamaxCrystalUma3323,
    DynamaxCrystalUma4033,
    DynamaxCrystalUma4377,
    DynamaxCrystalUma4375,
    DynamaxCrystalUma4518,
    DynamaxCrystalUma3594,
    DynamaxCrystalVir5056,
    DynamaxCrystalVir4825,
    DynamaxCrystalVir4932,
    DynamaxCrystalVir4540,
    DynamaxCrystalVir4689,
    DynamaxCrystalVir5338,
    DynamaxCrystalVir4910,
    DynamaxCrystalVir5315,
    DynamaxCrystalVir5359,
    DynamaxCrystalVir5409,
    DynamaxCrystalVir5107,
    DynamaxCrystalAri617,
    DynamaxCrystalAri553,
    DynamaxCrystalAri546,
    DynamaxCrystalAri951,
    DynamaxCrystalOri1713,
    DynamaxCrystalOri2061,
    DynamaxCrystalOri1790,
    DynamaxCrystalOri1903,
    DynamaxCrystalOri1948,
    DynamaxCrystalOri2004,
    DynamaxCrystalOri1852,
    DynamaxCrystalOri1879,
    DynamaxCrystalOri1899,
    DynamaxCrystalOri1543,
    DynamaxCrystalCas21,
    DynamaxCrystalCas168,
    DynamaxCrystalCas403,
    DynamaxCrystalCas153,
    DynamaxCrystalCas542,
    DynamaxCrystalCas219,
    DynamaxCrystalCas265,
    DynamaxCrystalCnc3572,
    DynamaxCrystalCnc3208,
    DynamaxCrystalCnc3461,
    DynamaxCrystalCnc3449,
    DynamaxCrystalCnc3429,
    DynamaxCrystalCnc3627,
    DynamaxCrystalCnc3268,
    DynamaxCrystalCnc3249,
    DynamaxCrystalCom4968,
    DynamaxCrystalCrv4757,
    DynamaxCrystalCrv4623,
    DynamaxCrystalCrv4662,
    DynamaxCrystalCrv4786,
    DynamaxCrystalAur1708,
    DynamaxCrystalAur2088,
    DynamaxCrystalAur1605,
    DynamaxCrystalAur2095,
    DynamaxCrystalAur1577,
    DynamaxCrystalAur1641,
    DynamaxCrystalAur1612,
    DynamaxCrystalPav7790,
    DynamaxCrystalCet911,
    DynamaxCrystalCet681,
    DynamaxCrystalCet188,
    DynamaxCrystalCet539,
    DynamaxCrystalCet804,
    DynamaxCrystalCep8974,
    DynamaxCrystalCep8162,
    DynamaxCrystalCep8238,
    DynamaxCrystalCep8417,
    DynamaxCrystalCen5267,
    DynamaxCrystalCen5288,
    DynamaxCrystalCen551,
    DynamaxCrystalCen5459,
    DynamaxCrystalCen5460,
    DynamaxCrystalCmi2943,
    DynamaxCrystalCmi2845,
    DynamaxCrystalEqu8131,
    DynamaxCrystalVul7405,
    DynamaxCrystalUmi424,
    DynamaxCrystalUmi5563,
    DynamaxCrystalUmi5735,
    DynamaxCrystalUmi6789,
    DynamaxCrystalCrt4287,
    DynamaxCrystalLyr7001,
    DynamaxCrystalLyr7178,
    DynamaxCrystalLyr7106,
    DynamaxCrystalLyr7298,
    DynamaxCrystalAra6585,
    DynamaxCrystalSco6134,
    DynamaxCrystalSco6527,
    DynamaxCrystalSco6553,
    DynamaxCrystalSco5953,
    DynamaxCrystalSco5984,
    DynamaxCrystalSco6508,
    DynamaxCrystalSco6084,
    DynamaxCrystalSco5944,
    DynamaxCrystalSco6630,
    DynamaxCrystalSco6027,
    DynamaxCrystalSco6247,
    DynamaxCrystalSco6252,
    DynamaxCrystalSco5928,
    DynamaxCrystalSco6241,
    DynamaxCrystalSco6165,
    DynamaxCrystalTri544,
    DynamaxCrystalLeo3982,
    DynamaxCrystalLeo4534,
    DynamaxCrystalLeo4357,
    DynamaxCrystalLeo4057,
    DynamaxCrystalLeo4359,
    DynamaxCrystalLeo4031,
    DynamaxCrystalLeo3852,
    DynamaxCrystalLeo3905,
    DynamaxCrystalLeo3773,
    DynamaxCrystalGru8425,
    DynamaxCrystalGru8636,
    DynamaxCrystalGru8353,
    DynamaxCrystalLib5685,
    DynamaxCrystalLib5531,
    DynamaxCrystalLib5787,
    DynamaxCrystalLib5603,
    DynamaxCrystalPup3165,
    DynamaxCrystalPup3185,
    DynamaxCrystalPup3045,
    DynamaxCrystalCyg7924,
    DynamaxCrystalCyg7417,
    DynamaxCrystalCyg7796,
    DynamaxCrystalCyg8301,
    DynamaxCrystalCyg7949,
    DynamaxCrystalCyg7528,
    DynamaxCrystalOct7228,
    DynamaxCrystalCol1956,
    DynamaxCrystalCol2040,
    DynamaxCrystalCol2177,
    DynamaxCrystalGem2990,
    DynamaxCrystalGem2891,
    DynamaxCrystalGem2421,
    DynamaxCrystalGem2473,
    DynamaxCrystalGem2216,
    DynamaxCrystalGem2777,
    DynamaxCrystalGem2650,
    DynamaxCrystalGem2286,
    DynamaxCrystalGem2484,
    DynamaxCrystalGem2930,
    DynamaxCrystalPeg8775,
    DynamaxCrystalPeg8781,
    DynamaxCrystalPeg39,
    DynamaxCrystalPeg8308,
    DynamaxCrystalPeg8650,
    DynamaxCrystalPeg8634,
    DynamaxCrystalPeg8684,
    DynamaxCrystalPeg8450,
    DynamaxCrystalPeg8880,
    DynamaxCrystalPeg8905,
    DynamaxCrystalOph6556,
    DynamaxCrystalOph6378,
    DynamaxCrystalOph6603,
    DynamaxCrystalOph6149,
    DynamaxCrystalOph6056,
    DynamaxCrystalOph6075,
    DynamaxCrystalSer5854,
    DynamaxCrystalSer7141,
    DynamaxCrystalSer5879,
    DynamaxCrystalHer6406,
    DynamaxCrystalHer6148,
    DynamaxCrystalHer6410,
    DynamaxCrystalHer6526,
    DynamaxCrystalHer6117,
    DynamaxCrystalHer6008,
    DynamaxCrystalPer936,
    DynamaxCrystalPer1017,
    DynamaxCrystalPer1131,
    DynamaxCrystalPer1228,
    DynamaxCrystalPer834,
    DynamaxCrystalPer941,
    DynamaxCrystalPhe99,
    DynamaxCrystalPhe338,
    DynamaxCrystalVel3634,
    DynamaxCrystalVel3485,
    DynamaxCrystalVel3734,
    DynamaxCrystalAqr8232,
    DynamaxCrystalAqr8414,
    DynamaxCrystalAqr8709,
    DynamaxCrystalAqr8518,
    DynamaxCrystalAqr7950,
    DynamaxCrystalAqr8499,
    DynamaxCrystalAqr8610,
    DynamaxCrystalAqr8264,
    DynamaxCrystalCru4853,
    DynamaxCrystalCru4730,
    DynamaxCrystalCru4763,
    DynamaxCrystalCru4700,
    DynamaxCrystalCru4656,
    DynamaxCrystalPsa8728,
    DynamaxCrystalTra6217,
    DynamaxCrystalCap7776,
    DynamaxCrystalCap7754,
    DynamaxCrystalCap8278,
    DynamaxCrystalCap8322,
    DynamaxCrystalCap7773,
    DynamaxCrystalSge7479,
    DynamaxCrystalCar2326,
    DynamaxCrystalCar3685,
    DynamaxCrystalCar3307,
    DynamaxCrystalCar3699,
    DynamaxCrystalDra5744,
    DynamaxCrystalDra5291,
    DynamaxCrystalDra6705,
    DynamaxCrystalDra6536,
    DynamaxCrystalDra7310,
    DynamaxCrystalDra6688,
    DynamaxCrystalDra4434,
    DynamaxCrystalDra6370,
    DynamaxCrystalDra7462,
    DynamaxCrystalDra6396,
    DynamaxCrystalDra6132,
    DynamaxCrystalDra6636,
    DynamaxCrystalCvn4915,
    DynamaxCrystalCvn4785,
    DynamaxCrystalCvn4846,
    DynamaxCrystalAql7595,
    DynamaxCrystalAql7557,
    DynamaxCrystalAql7525,
    DynamaxCrystalAql7602,
    DynamaxCrystalAql7235,
    MaxHoney,
    MaxMushrooms,
    GalaricaTwig,
    GalaricaCuff,
    StyleCard,
    ArmorPass,
    RotomBikeSparklingWhite,
    RotomBikeGlisteningBlack,
    ExpCharm,
    ArmoriteOre,
    MarkCharm,
    ReinsOfUnityMerge,
    ReinsOfUnitySplit,
    GalaricaWreath,
    LegendaryClue1,
    LegendaryClue2,
    LegendaryClue3,
    LegendaryClueQuestion,
    CrownPass,
    WoodenCrown,
    RadiantPetal,
    WhiteManeHair,
    BlackManeHair,
    IcerootCarrot,
    ShaderootCarrot,
    DyniteOre,
    CarrotSeeds,
    AbilityPatch,
    ReinsOfUnity,
    AdamantCrystal,
    LustrousGlobe,
    GriseousCore,
    BlankPlate,
    StrangeBall,
    LegendPlate,
    RotomPhone,
    Sandwich,
    KoraidonsPokeBall,
    MiraidonsPokeBall,
    TeraOrb,
    ScarletBook,
    VioletBook,
    KofusWallet,
    TinyBambooShoot,
    BigBambooShoot,
    ScrollOfDarkness,
    ScrollOfWaters,
    MaliciousArmor,
    NormalTeraShard,
    FireTeraShard,
    WaterTeraShard,
    ElectricTeraShard,
    GrassTeraShard,
    IceTeraShard,
    FightingTeraShard,
    PoisonTeraShard,
    GroundTeraShard,
    FlyingTeraShard,
    PsychicTeraShard,
    BugTeraShard,
    RockTeraShard,
    GhostTeraShard,
    DragonTeraShard,
    DarkTeraShard,
    SteelTeraShard,
    FairyTeraShard,
    BoosterEnergy,
    AbilityShield,
    ClearAmulet,
    MirrorHerb,
    PunchingGlove,
    CovertCloak,
    LoadedDice,
    Baguette,
    Mayonnaise,
    Ketchup,
    Mustard,
    Butter,
    PeanutButter,
    ChiliSauce,
    Salt,
    Pepper,
    Yogurt,
    WhippedCream,
    CreamCheese,
    Jam,
    Marmalade,
    OliveOil,
    Vinegar,
    SweetHerbaMystica,
    SaltyHerbaMystica,
    SourHerbaMystica,
    BitterHerbaMystica,
    SpicyHerbaMystica,
    Lettuce,
    Tomato,
    CherryTomatoes,
    Cucumber,
    Pickle,
    Onion,
    RedOnion,
    GreenBellPepper,
    RedBellPepper,
    YellowBellPepper,
    Avocado,
    Bacon,
    Ham,
    Prosciutto,
    Chorizo,
    HerbedSausage,
    Hamburger,
    KlawfStick,
    SmokedFillet,
    FriedFillet,
    Egg,
    PotatoTortilla,
    Tofu,
    Rice,
    Noodles,
    PotatoSalad,
    Cheese,
    Banana,
    Strawberry,
    Apple,
    Kiwi,
    Pineapple,
    Jalapeño,
    Horseradish,
    CurryPowder,
    Wasabi,
    Watercress,
    Basil,
    VenonatFang,
    DiglettDirt,
    MeowthFur,
    PsyduckDown,
    MankeyFur,
    GrowlitheFur,
    SlowpokeClaw,
    MagnemiteScrew,
    GrimerToxin,
    ShellderPearl,
    GastlyGas,
    DrowzeeFur,
    VoltorbSparks,
    ScytherClaw,
    TaurosHair,
    MagikarpScales,
    DittoGoo,
    EeveeFur,
    DratiniScales,
    PichuFur,
    IgglybuffFluff,
    MareepWool,
    HoppipLeaf,
    SunkernLeaf,
    MurkrowBauble,
    MisdreavusTears,
    GirafarigFur,
    PinecoHusk,
    DunsparceScales,
    QwilfishSpines,
    HeracrossClaw,
    SneaselClaw,
    TeddiursaClaw,
    DelibirdParcel,
    HoundourFang,
    PhanpyNail,
    StantlerHair,
    LarvitarClaw,
    WingullFeather,
    RaltsDust,
    SurskitSyrup,
    ShroomishSpores,
    SlakothFur,
    MakuhitaSweat,
    AzurillFur,
    SableyeGem,
    MedititeSweat,
    GulpinMucus,
    NumelLava,
    TorkoalCoal,
    SpoinkPearl,
    CacneaNeedle,
    SwabluFluff,
    ZangooseClaw,
    SeviperFang,
    BarboachSlime,
    ShuppetScrap,
    TropiusLeaf,
    SnoruntFur,
    LuvdiscScales,
    BagonScales,
    StarlyFeather,
    KricketotShell,
    ShinxFang,
    CombeeHoney,
    PachirisuFur,
    BuizelFur,
    ShellosMucus,
    DrifloonGas,
    StunkyFur,
    BronzorFragment,
    BonslyTears,
    HappinyDust,
    SpiritombFragment,
    GibleScales,
    RioluFur,
    HippopotasSand,
    CroagunkPoison,
    FinneonScales,
    SnoverBerries,
    RotomSparks,
    PetililLeaf,
    BasculinFang,
    SandileClaw,
    ZoruaFur,
    GothitaEyelash,
    DeerlingHair,
    FoongusSpores,
    AlomomolaMucus,
    TynamoSlime,
    AxewScales,
    CubchooFur,
    CryogonalIce,
    PawniardBlade,
    RuffletFeather,
    DeinoScales,
    LarvestaFuzz,
    FletchlingFeather,
    ScatterbugPowder,
    LitleoTuft,
    FlabebePollen,
    SkiddoLeaf,
    SkrelpKelp,
    ClauncherClaw,
    HawluchaDown,
    DedenneFur,
    GoomyGoo,
    KlefkiKey,
    BergmiteIce,
    NoibatFur,
    YungoosFur,
    CrabrawlerShell,
    OricorioFeather,
    RockruffRock,
    MareanieSpike,
    MudbrayMud,
    FomantisLeaf,
    SalanditGas,
    BounsweetSweat,
    OranguruFur,
    PassimianFur,
    SandygastSand,
    KomalaClaw,
    MimikyuScrap,
    BruxishTooth,
    ChewtleClaw,
    SkwovetFur,
    ArrokudaScales,
    RookideeFeather,
    ToxelSparks,
    FalinksSweat,
    CufantTarnish,
    RolycolyCoal,
    SilicobraSand,
    IndeedeeFur,
    PincurchinSpines,
    SnomThread,
    ImpidimpHair,
    ApplinJuice,
    SinisteaChip,
    HatennaDust,
    StonjournerStone,
    EiscueDown,
    DreepyPowder,
    LechonkHair,
    TarountulaThread,
    NymbleClaw,
    RellorMud,
    GreavardWax,
    FlittleDown,
    WiglettSand,
    DondozoWhisker,
    VeluzaFillet,
    FinizenMucus,
    SmolivOil,
    CapsakidSeed,
    TadbulbMucus,
    VaroomFume,
    OrthwormTarnish,
    TandemausFur,
    CetoddleGrease,
    FrigibaxScales,
    TatsugiriScales,
    CyclizarScales,
    PawmiFur,
    WattrelFeather,
    BombirdierFeather,
    SquawkabillyFeather,
    FlamigoDown,
    KlawfClaw,
    NacliSalt,
    GlimmetCrystal,
    ShroodleInk,
    FidoughFur,
    MaschiffFang,
    BramblinTwig,
    GimmighoulCoin,
    TinkatinkHair,
    CharcadetSoot,
    ToedscoolFlaps,
    WooperSlime,
    Tm100_,
    Tm101,
    Tm102,
    Tm103,
    Tm104,
    Tm105,
    Tm106,
    Tm107,
    Tm108,
    Tm109,
    Tm110,
    Tm111,
    Tm112,
    Tm113,
    Tm114,
    Tm115,
    Tm116,
    Tm117,
    Tm118,
    Tm119,
    Tm120,
    Tm121,
    Tm122,
    Tm123,
    Tm124,
    Tm125,
    Tm126,
    Tm127,
    Tm128,
    Tm129,
    Tm130,
    Tm131,
    Tm132,
    Tm133,
    Tm134,
    Tm135,
    Tm136,
    Tm137,
    Tm138,
    Tm139,
    Tm140,
    Tm141,
    Tm142,
    Tm143,
    Tm144,
    Tm145,
    Tm146,
    Tm147,
    Tm148,
    Tm149,
    Tm150,
    Tm151,
    Tm152,
    Tm153,
    Tm154,
    Tm155,
    Tm156,
    Tm157,
    Tm158,
    Tm159,
    Tm160,
    Tm161,
    Tm162,
    Tm163,
    Tm164,
    Tm165,
    Tm166,
    Tm167,
    Tm168,
    Tm169,
    Tm170,
    Tm171,
    PicnicSet,
    AcademyBottle,
    AcademyBottle_,
    PolkaDotBottle,
    StripedBottle,
    DiamondBottle,
    AcademyCup,
    AcademyCup2,
    StripedCup,
    PolkaDotCup,
    FlowerPatternCup,
    AcademyTablecloth,
    AcademyTablecloth_,
    WhimsicalTablecloth,
    LeafyTablecloth,
    SpookyTablecloth,
    AcademyBall,
    AcademyBall_,
    MarillBall,
    YarnBall,
    CyberBall,
    GoldPick,
    SilverPick,
    RedFlagPick,
    BlueFlagPick,
    PikaPikaPick,
    WinkingPikaPick,
    VeeVeePick,
    SmilingVeePick,
    BluePokeBallPick,
    AuspiciousArmor,
    LeadersCrest,
    PinkBottle,
    BlueBottle,
    YellowBottle,
    SteelBottleR,
    SteelBottleY,
    SteelBottleB,
    SilverBottle,
    BarredCup,
    DiamondPatternCup,
    FirePatternCup,
    PinkCup,
    BlueCup,
    YellowCup,
    PikachuCup,
    EeveeCup,
    SlowpokeCup,
    SilverCup,
    ExerciseBall,
    PlaidTableclothY,
    PlaidTableclothB,
    PlaidTableclothR,
    BWGrassTablecloth,
    BattleTablecloth,
    MonstrousTablecloth,
    StripedTablecloth,
    DiamondTablecloth,
    PolkaDotTablecloth,
    LilacTablecloth,
    MintTablecloth,
    PeachTablecloth,
    YellowTablecloth,
    BlueTablecloth,
    PinkTablecloth,
    GoldBottle,
    BronzeBottle,
    GoldCup,
    BronzeCup,
    GreenPokeBallPick,
    RedPokeBallPick,
    PartySparklerPick,
    HeroicSwordPick,
    MagicalStarPick,
    MagicalHeartPick,
    ParasolPick,
    BlueSkyFlowerPick,
    SunsetFlowerPick,
    SunriseFlowerPick,
    BlueDish,
    GreenDish,
    OrangeDish,
    RedDish,
    WhiteDish,
    YellowDish,
    RotoStick,
    TealStyleCard,
    TealMask,
    GlimmeringCharm,
    CyrstalCluster,
    FairyFeather,
    WellspringMask,
    HearthflameMask,
    CornerstoneMask,
    SyrupyApple,
    UnremarkableTeacup,
    MasterpieceTeacup,
    HealthMochi,
    MuscleMochi,
    ResistMochi,
    GeniusMochi,
    CleverMochi,
    SwiftMochi,
    FreshStartMochi,
    EkansFang,
    SandshrewClaw,
    CleffaFur,
    VulpixFur,
    PoliwagSlime,
    BellsproutVine,
    GeodudeFragment,
    KoffingGas,
    MunchlaxFang,
    SentretFur,
    HoothootFeather,
    SpinarakThread,
    AipomHair,
    YanmaSpike,
    GligarFang,
    SlugmaLava,
    SwinubHair,
    PoochyenaFang,
    LotadLeaf,
    SeedotStem,
    NosepassFragment,
    VolbeatFluid,
    IllumiseFluid,
    CorphishShell,
    FeebasScales,
    DuskullFragment,
    ChinglingFragment,
    TimburrSweat,
    SewaddleLeaf,
    DucklettFeather,
    LitwickSoot,
    MienfooClaw,
    VullabyFeather,
    CarbinkJewel,
    PhantumpTwig,
    GrubbinThread,
    CutieflyPowder,
    JangmoOScales,
    CramorantDown,
    MorpekoSnack,
    PoltchageistPowder,
    LinkingCord,
    Tm172,
    Tm173,
    Tm174,
    Tm175,
    Tm176,
    Tm177,
    Tm178,
    Tm179,
    Tm180,
    Tm181,
    Tm182,
    Tm183,
    Tm184,
    Tm185,
    Tm186,
    Tm187,
    Tm188,
    Tm189,
    Tm190,
    Tm191,
    Tm192,
    Tm193,
    Tm194,
    Tm195,
    Tm196,
    Tm197,
    Tm198,
    Tm199,
    Tm200,
    Tm201,
    Tm202,
    Tm203,
    Tm204,
    Tm205,
    Tm206,
    Tm207,
    Tm208,
    Tm209,
    Tm210,
    Tm211,
    Tm212,
    Tm213,
    Tm214,
    Tm215,
    Tm216,
    Tm217,
    Tm218,
    Tm219,
    Tm220,
    Tm221,
    Tm222,
    Tm223,
    Tm224,
    Tm225,
    Tm226,
    Tm227,
    Tm228,
    Tm229,
    LastrangeBall,
    LapokeBall,
    LagreatBall,
    LaultraBall,
    LaheavyBall,
    LaleadenBall,
    LagigatonBall,
    LafeatherBall,
    LawingBall,
    LajetBall,
    LaoriginBall,
    BlackAugurite = 10001,
    PeatBlock,
}

impl Item {
    pub fn from_db_id(id: ID) -> Self {
        unsafe {std::mem::transmute(id)}
    }
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum MoveTarget {
    SpecificMove = 1,
    SelectedPokemonMeFirst,
    Ally,
    UsersField,
    UserOrAlly,
    OpponentsField,
    User,
    RandomOpponent,
    AllOtherPokemon,
    SelectedPokemon,
    AllOpponents,
    EntireField,
    UserAndAllies,
    AllPokemon,
    AllAllies
}

impl MoveTarget {
    pub fn from_db_id(id: u8) -> Self {
        unsafe {std::mem::transmute(id)}
    }
}

#[repr(u16)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum MoveEffect {
    NoEffect1 = 1,
    Sleep,
    PoisonChance,
    DrainHalf,
    BurnChance,
    FreezeChance,
    ParalyzeChance,
    FaintUser,
    DreamEater,
    UseTargetsLastMove,
    RaiseUserAttack1,
    RaiseUserDefense1,
    RaiseUserSpecialAttack1 = 14,
    RaiseUserEvasion1 = 17,
    NeverMiss,
    LowerTargetAttack1,
    LowerTargetDefense1,
    LowerTargetSpeed1,
    LowerTargetAccuracy1 = 24,
    LowerTargetEvasion1,
    ResetTargetStats,
    Bide,
    Outrage,
    ForceSwitch,
    Hit2To5Times,
    Conversion,
    FlinchChance,
    HealUserHalf,
    BadlyPoison,
    ScatterMoney,
    LightScreen,
    TriAttack,
    Rest,
    OHKO,
    RazorWind,
    SuperFang,
    DragonRage,
    Trapping,
    IncreasedCrit,
    HitTwice,
    RecoilOnMiss,
    ProtectStats,
    FocusEnergy,
    RecoilQuarter,
    Confuse,
    RaiseUserAttack2,
    RaiseUserDefense2,
    RaiseUserSpeed2,
    RaiseUserSpecialAttack2,
    RaiseUserSpecialDefense2,
    Transform = 58,
    LowerTargetAttack2,
    LowerTargetDefense2,
    LowerTargetSpeed2,
    LowerTargetSpecialAttack2,
    LowerTargetSpecialDefense2,
    Reflect = 66,
    Poison,
    Paralyze,
    LowerTargetAttack1Chance,
    LowerTargetDefense1Chance,
    LowerTargetSpeed1Chance,
    LowerTargetSpecialAttack1Chance,
    LowerTargetSpecialDefense1Chance,
    LowerTargetAccuracy1Chance,
    MysticalFire,
    ChargeAndFlinchChance,
    ConfuseChance,
    HitTwiceAndPoisonChance,
    NeverMiss2,
    Substitute,
    Recharge,
    RaiseAttack1IfHit,
    UseTargetsLastMove2,
    Metronome,
    Seed,
    Splash,
    Disable,
    DamageByLevel,
    RangeDamageByLevel,
    Counter,
    Encore,
    PainSplit,
    FlinchChanceWorksIfSleeping,
    Transform2,
    NextMoveHits,
    Sketch,
    SleepTalk = 98,
    DestinyBond,
    MorePowerWhenLessHP,
    Spite,
    FalseSwipe,
    CurePartyStatus,
    NoOtherEffect2,
    Hit3TimesIncreasing,
    StealItem,
    PreventEscape,
    Nightmare,
    Minimize,
    Curse = 112,
    Protect,
    Spikes,
    Identify,
    PerishSong,
    Sandstorm,
    Endure,
    Rollout,
    Swagger,
    IceBall,
    Attract,
    Return,
    Present,
    Frustration,
    Safeguard,
    Magnitude,
    BatonPass,
    Pursuit,
    RapidSpin,
    SonicBoom,
    Moonlight = 133,
    HiddenPower = 136,
    RainDance,
    SunnyDay,
    RaiseUserDefense1Chance,
    RaiseUserAttack1Chance,
    RaiseAllUserStats1Chance,
    BellyDrum = 143,
    PsychUp,
    MirrorCoat,
    SkullBash,
    Twister,
    Earthquake,
    Hits2TurnsLater,
    Gust,
    Stomp,
    Solarbeam,
    Thunder,
    Teleport,
    BeatUp,
    Fly,
    DefenseCurl,
    FakeOut = 159,
    Uproar,
    Stockpile,
    SpitUp,
    Swallow,
    Hail = 165,
    Torment,
    Flatter,
    Burn,
    Memento,
    Facade,
    FocusPunch,
    SmellingSalts,
    FollowMe,
    NaturePower,
    Charge,
    Taunt,
    HelpingHand,
    Trick,
    RolePlay,
    Wish,
    RandomlySwitchOutTarget,
    Ingrain,
    LowerUserAttackDefense1,
    MagicCoat,
    Recycle,
    DoubleDamageIfHitBeforeAttacking,
    DestroyScreens,
    Yawn,
    KnockOff,
    Endeavor,
    PowerBasedOnUserHP,
    SkillSwap,
    Imprison,
    HealUserStatus,
    Grudge,
    Snatch,
    PowerBasedOnWeight,
    SecretPower,
    RecoilThird,
    ConfuseAllTargets,
    IncreasedCritAndBurnChance,
    MudSport,
    BadlyPoisonChance,
    WeatherBall,
    LowerUserSpecialAttack,
    LowerTargetAttackDefense1,
    RaiseUserDefenseSpecialDefense1,
    HitBounceFly,
    RaiseUserAttackDefense1,
    IncreasedCritAndPoisonChance,
    WaterSport,
    RaiseUserSpecialAttackSpecialDefense1,
    RaiseUserAttackSpeed1,
    Camouflage,
    Roost,
    Gravity,
    MiracleEye,
    WakeUpSlap,
    LowerUserSpeed1,
    GyroBall,
    HealingWish,
    Brine,
    NaturalGift,
    Feint,
    Pluck,
    Tailwind,
    Acupressure,
    MetalBurst,
    SwitchAfterAttacking,
    LowerUserDefenseSpecialDefense1,
    DoublePowerIfTargetAlreadyMoved,
    DoublePowerIfTargetAlreadyTookDamage,
    Embargo,
    Fling,
    PsychoShift,
    TrumpCard,
    HealBlock,
    PowerBasedOnTargetHP,
    PowerTrick,
    GastroAcid,
    LuckyChant,
    MeFirst,
    Copycat,
    PowerSwap,
    GuardSwap,
    Punishment,
    LastResort,
    WorrySeed,
    SuckerPunch,
    ToxicSpikes,
    HeartSwap,
    AquaRing,
    MagnetRise,
    FlareBlitz,
    Struggle,
    Dive,
    Dig,
    Surf,
    Defog,
    TrickRoom,
    Blizzard,
    Whirlpool,
    VoltTackle,
    Bounce,
    Captivate = 266,
    StealthRock,
    Chatter,
    TypeBasedOnDriveOrPlate,
    RecoilHalf,
    LunarDance,
    LowerTargetSpecialDefense2Chance,
    Disappear1TurnIgnoreProtect,
    FireFang,
    IceFang,
    ThunderFang,
    RaiseUserSpecialAttack1Chance,
    HoneClaws,
    WideGuard,
    GuardSplit,
    PowerSplit,
    WonderRoom,
    Psyshock,
    Venoshock,
    Autotomize,
    Telekinesis,
    MagicRoom,
    SmackDown,
    AlwaysCrits,
    SplashDamage,
    QuiverDance,
    HeavySlam,
    HitIfTypesShared,
    PowerBasedOnSpeedDifference,
    Soak,
    RaiseUserSpeed1,
    AcidSpray,
    FoulPlay,
    SimpleBeam,
    Entrainment,
    AfterYou,
    Round,
    EchoedVoice,
    DarkestLariat,
    ClearSmog,
    PowerTrip,
    QuickGuard,
    AllySwitch,
    ShellSmash,
    HealPulse,
    Hex,
    SkyDrop,
    ShiftGear,
    Roar,
    Incinerate,
    Quash,
    Growth,
    Acrobatics,
    ReflectType,
    Retaliate,
    FinalGambit,
    TailGlow,
    Coil,
    Thief,
    WaterPledge,
    FirePledge,
    GrassPledge,
    WorkUp,
    CottonGuard,
    RelicSong,
    RockTomb,
    FreezeShock,
    IceBurn,
    Hurricane,
    VCreate,
    FusionFlare,
    FusionBolt,
    FlyingPress,
    Belch,
    Rototiller,
    StickyWeb,
    FellStinger,
}

impl MoveEffect {
    pub fn from_db_id(id: ID) -> Self {
        unsafe {std::mem::transmute(id)}
    }
}